apiVersion: v1
kind: Namespace
metadata:
  name: poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-poc
  namespace: poc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cluster-poc
  template:
    metadata:
      labels:
        app: cluster-poc
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cluster-poc
                topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: test-secret
      containers:
        - name: app
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            [
              "/bin/sh",
              "-c",
              "while true; do echo 'Hello, world!'; sleep 1; done",
            ]
