global:
  storageClass: standard
  imagePullSecrets:
    - name: test-secret
manager:
  enable: true
  image:
    repository: dragonflyoss/manager
    tag: v2.2.1
  replicas: 3
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "2"
      memory: "4Gi"
  nodeSelector:
    kubernetes.io/hostname: desktop-worker
  metrics:
    enable: true
    serviceMonitor:
      enable: true
    prometheusRule:
      enable: false

  config:
    console: true
    verbose: true
    pprofPort: -1

scheduler:
  enable: true
  image:
    repository: dragonflyoss/scheduler
    tag: v2.2.1
  replicas: 3
  nodeSelector:
    kubernetes.io/hostname: desktop-worker
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "4"
      # use 8Gi at least on production
      memory: "4Gi"
  metrics:
    enable: true
    serviceMonitor:
      enable: true
    prometheusRule:
      enable: false
  config:
    console: true
    verbose: true
    pprofPort: -1
    scheduler:
      retryBackToSourceLimit: 5
      retryLimit: 7
      retryInterval: 800ms

seedClient:
  enable: true
  image:
    repository: dragonflyoss/client
    tag: v0.2.19
  replicas: 3
  nodeSelector:
    kubernetes.io/hostname: desktop-worker
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "2"
      memory: "4Gi"
  persistence:
    enable: true
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 10Gi #10Gi for testing, use 50Gi at least in production
    storageClass: standard
  #collect metrics to datadog: https://docs.datadoghq.com/containers/kubernetes/prometheus/?tab=kubernetesadv2
  podAnnotations:
    ad.datadoghq.com/seed-client.checks: |
      {
        "openmetrics": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:4002/metrics",
              "namespace": "dragonfly",
              "metrics": ["dragonfly*"]
            }
          ]
        }
      }
  metrics:
    enable: true
    serviceMonitor:
      enable: true
    prometheusRule:
      enable: false
  config:
    download:
      pieceTimeout: 600s #default 30s is not suit for big image piece download
    console: true
    verbose: true

client:
  enable: true
  image:
    repository: dragonflyoss/client
    tag: v0.2.19
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "2"
      memory: "4Gi"
  metrics:
    enable: true
    serviceMonitor:
      enable: true
    prometheusRule:
      enable: false
  config:
    proxy:
      prefetch: true
    download:
      #default 30s is not suit for big image piece download
      pieceTimeout: 600s
    console: true
    verbose: true
  dfinit:
    enable: true
    image:
      repository: dragonflyoss/dfinit
      tag: v0.2.19
    config:
      containerRuntime:
        containerd:
          configPath: /etc/containerd/config.toml
          registries:
            - hostNamespace: docker.io
              serverAddr: https://index.docker.io
              capabilities: ["pull", "resolve"]
              skipVerify: true
redis:
  master:
    nodeSelector:
      kubernetes.io/hostname: desktop-worker
    persistence:
      # use 8Gi at least on production
      size: 4Gi
  replica:
    nodeSelector:
      kubernetes.io/hostname: desktop-worker
    # use 2 at least on production
    replicaCount: 1
    persistence:
      # use 8Gi at least on production
      size: 4Gi
  global:
    storageClass: standard
mysql:
  primary:
    nodeSelector:
      kubernetes.io/hostname: desktop-worker
    persistence:
      # use 8Gi at least on production
      size: 4Gi
  secondary:
    nodeSelector:
      kubernetes.io/hostname: desktop-worker
    persistence:
      # use 8Gi at least on production
      size: 4Gi
  global:
    storageClass: standard
